version: '3.9'

services:
  fastapi:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: nexxus_fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./AZURE_layer2:/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: nexxus_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nexxdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: