services:
  weaviate:
    image: semitechnologies/weaviate:1.25.3
    restart: always
    container_name: nexxus-db
    ports:
      - "8080:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-openai'
      ENABLE_MODULES: 'text2vec-openai'
      OPENAI_APIKEY: ${OPENAI_API_KEY}  # Pulls from your env/.env
      
    volumes:
      - weaviate_data:/var/lib/weaviate

  fastapi:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: nexxus-api
    ports:
      - "8000:80"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      WEAVIATE_URL: http://weaviate:8080
      NEXXUS_PORT: 1337
    depends_on:
      weaviate:
        condition: service_started # Change to service_started if healthcheck is removed
    env_file: # Load environment variables from .env file
      - .env

volumes:
  weaviate_data:
