services:
  weaviate: # Changed service name from 'db' to 'weaviate' to match its usage
    container_name: nexxus_weaviate
    image: semitechnologies/weaviate:1.25.3 # Assuming this is your vector DB
    restart: always
    ports:
      - "8080:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-openai'
      ENABLE_MODULES: 'text2vec-openai'
      OPENAI_APIKEY: ${OPENAI_API_KEY}
      CLUSTER_HOSTNAME: 'node1'
    env_file: .env # Explicitly state that .env file provides variables
    volumes:
      - weaviate_data:/var/lib/weaviate
    networks:
      - nexxus_network

  fastapi:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        - PIP_RETRIES=5
    restart: always
    container_name: nexxus_fastapi
    ports:
      - "8000:80"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      WEAVIATE_URL: http://weaviate:8080
      NEXXUS_PORT: 1337
      
    env_file: .env # Explicitly state that .env file provides variables
    depends_on:
      - weaviate # Ensures weaviate starts before fastapi
    networks:
      - nexxus_network
    
volumes:
  weaviate_data:

networks:
  nexxus_network:
    driver: bridge
