services:
  weaviate:
    image: semitechnologies/weaviate:1.25.3
    restart: always
    container_name: nexxus-db
    ports:
      - "8080:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-openai'
      ENABLE_MODULES: 'text2vec-openai'
      OPENAI_APIKEY: ${OPENAI_API_KEY}  # Pulls from your env/.env

      
    volumes:
      - weaviate_data:/var/lib/weaviate
    healthcheck: # Added healthcheck for Weaviate
        test: ["CMD-SHELL", "wget -q --spider --timeout=10 http://localhost:8080/v1/.well-known/live || exit 1"]
        interval: 5s
        timeout: 10s
        retries: 5
        start_period: 10s 
      

  fastapi:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: nexxus-api
    ports:
      - "8000:80"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      WEAVIATE_URL: http://weaviate:8080
    depends_on:
      weaviate:
        condition: service_healthy # Change to service_started if healthcheck is removed
    env_file: # Load environment variables from .env file
      - .env

volumes:
  weaviate_data:
