name = "version1-1"
main = "src/index.ts"
compatibility_date = "2024-10-27"
compatibility_flags = [ "nodejs_compat" ]

# [vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNmY1Zjg5YWMtMDI0My00ZDY3LTlmYmYtODc4NzM4MWU2ZjM3IiwidGVuYW50X2lkIjoiOGEyODAzMjMwNWRhYjM0M2Q5MzhjODdhOGUzYjUzYTQyMjU1Yjc4Y2MzZDU1MTkzM2RhMGQxNWNhZTg0NzMxZSIsImludGVybmFsX3NlY3JldCI6Ijg4ZmJjOTg5LTliZmMtNDVjZC1iZWM4LWRkY2RhMDU4NTk4YyJ9.xKiR1mZ3A53JH6h_1HpHUFvrPSWW_iC4gl2LaFME7EU"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1